package Proyecto1.entity;
// Generated 2/12/2018 04:37:45 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable {


     private int idProducto;
     private Proveedor proveedor;
     private String nombre;
     private Integer numeroDeUnidadesExist;
     private Double precioUnitario;
     private String fechaIngreso;
     private Set ventaproductos = new HashSet(0);

    public Producto() {
    }

	
    public Producto(int idProducto) {
        this.idProducto = idProducto;
    }
    public Producto(int idProducto, Proveedor proveedor, String nombre, Integer numeroDeUnidadesExist, Double precioUnitario, String fechaIngreso, Set ventaproductos) {
       this.idProducto = idProducto;
       this.proveedor = proveedor;
       this.nombre = nombre;
       this.numeroDeUnidadesExist = numeroDeUnidadesExist;
       this.precioUnitario = precioUnitario;
       this.fechaIngreso = fechaIngreso;
       this.ventaproductos = ventaproductos;
    }
   
    public int getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(int idProducto) {
        this.idProducto = idProducto;
    }
    public Proveedor getProveedor() {
        return this.proveedor;
    }
    
    public void setProveedor(Proveedor proveedor) {
        this.proveedor = proveedor;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Integer getNumeroDeUnidadesExist() {
        return this.numeroDeUnidadesExist;
    }
    
    public void setNumeroDeUnidadesExist(Integer numeroDeUnidadesExist) {
        this.numeroDeUnidadesExist = numeroDeUnidadesExist;
    }
    public Double getPrecioUnitario() {
        return this.precioUnitario;
    }
    
    public void setPrecioUnitario(Double precioUnitario) {
        this.precioUnitario = precioUnitario;
    }
    public String getFechaIngreso() {
        return this.fechaIngreso;
    }
    
    public void setFechaIngreso(String fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }
    public Set getVentaproductos() {
        return this.ventaproductos;
    }
    
    public void setVentaproductos(Set ventaproductos) {
        this.ventaproductos = ventaproductos;
    }

}


