package Proyecto1.entity;
// Generated 2/12/2018 04:37:45 PM by Hibernate Tools 4.3.1



/**
 * Ventaproducto generated by hbm2java
 */
public class Ventaproducto  implements java.io.Serializable {


     private VentaproductoId id;
     private Producto producto;
     private Venta venta;
     private Integer num;

    public Ventaproducto() {
    }

	
    public Ventaproducto(VentaproductoId id, Producto producto, Venta venta) {
        this.id = id;
        this.producto = producto;
        this.venta = venta;
    }
    public Ventaproducto(VentaproductoId id, Producto producto, Venta venta, Integer num) {
       this.id = id;
       this.producto = producto;
       this.venta = venta;
       this.num = num;
    }
   
    public VentaproductoId getId() {
        return this.id;
    }
    
    public void setId(VentaproductoId id) {
        this.id = id;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public Venta getVenta() {
        return this.venta;
    }
    
    public void setVenta(Venta venta) {
        this.venta = venta;
    }
    public Integer getNum() {
        return this.num;
    }
    
    public void setNum(Integer num) {
        this.num = num;
    }




}


