package Proyecto1.entity;
// Generated 2/12/2018 04:37:45 PM by Hibernate Tools 4.3.1



/**
 * VentaproductoId generated by hbm2java
 */
public class VentaproductoId  implements java.io.Serializable {


     private int idVenta;
     private int idProducto;

    public VentaproductoId() {
    }

    public VentaproductoId(int idVenta, int idProducto) {
       this.idVenta = idVenta;
       this.idProducto = idProducto;
    }
   
    public int getIdVenta() {
        return this.idVenta;
    }
    
    public void setIdVenta(int idVenta) {
        this.idVenta = idVenta;
    }
    public int getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(int idProducto) {
        this.idProducto = idProducto;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof VentaproductoId) ) return false;
		 VentaproductoId castOther = ( VentaproductoId ) other; 
         
		 return (this.getIdVenta()==castOther.getIdVenta())
 && (this.getIdProducto()==castOther.getIdProducto());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdVenta();
         result = 37 * result + this.getIdProducto();
         return result;
   }   


}


