package Proyecto1.entity;
// Generated 2/12/2018 04:37:45 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Venta generated by hbm2java
 */
public class Venta  implements java.io.Serializable {


     private int idVenta;
     private Usuario usuario;
     private Double montoVenta;
     private String tipoPago;
     private String fechaVenta;
     private Set ventaproductos = new HashSet(0);

    public Venta() {
    }

	
    public Venta(int idVenta) {
        this.idVenta = idVenta;
    }
    public Venta(int idVenta, Usuario usuario, Double montoVenta, String tipoPago, String fechaVenta, Set ventaproductos) {
       this.idVenta = idVenta;
       this.usuario = usuario;
       this.montoVenta = montoVenta;
       this.tipoPago = tipoPago;
       this.fechaVenta = fechaVenta;
       this.ventaproductos = ventaproductos;
    }
   
    public int getIdVenta() {
        return this.idVenta;
    }
    
    public void setIdVenta(int idVenta) {
        this.idVenta = idVenta;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Double getMontoVenta() {
        return this.montoVenta;
    }
    
    public void setMontoVenta(Double montoVenta) {
        this.montoVenta = montoVenta;
    }
    public String getTipoPago() {
        return this.tipoPago;
    }
    
    public void setTipoPago(String tipoPago) {
        this.tipoPago = tipoPago;
    }
    public String getFechaVenta() {
        return this.fechaVenta;
    }
    
    public void setFechaVenta(String fechaVenta) {
        this.fechaVenta = fechaVenta;
    }
    public Set getVentaproductos() {
        return this.ventaproductos;
    }
    
    public void setVentaproductos(Set ventaproductos) {
        this.ventaproductos = ventaproductos;
    }




}


