
package Forms;

import Proyecto1.entity.Usuario;
import Proyecto1.util.HibernateUtil;
import java.util.HashSet;
import org.hibernate.Query;
import org.hibernate.Session;
import java.util.List;
import java.util.Set;
import javax.swing.JOptionPane;
import org.hibernate.HibernateException;

/**
 *
 * @author luis_
 */
public class InicioSesion extends javax.swing.JFrame {

    /**
     * Creates new form InicioSesion
     */
    public InicioSesion() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelUsuario = new javax.swing.JLabel();
        LabelPass = new javax.swing.JLabel();
        BtnAccesar = new javax.swing.JButton();
        TextUsuario = new javax.swing.JTextField();
        JSesion = new javax.swing.JLabel();
        btnMin = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        PasswordField = new javax.swing.JPasswordField();
        JFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelUsuario.setBackground(new java.awt.Color(255, 255, 255));
        LabelUsuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LabelUsuario.setForeground(new java.awt.Color(255, 255, 255));
        LabelUsuario.setText("Usuario");
        getContentPane().add(LabelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, -1, -1));

        LabelPass.setBackground(new java.awt.Color(255, 255, 255));
        LabelPass.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LabelPass.setForeground(new java.awt.Color(255, 255, 255));
        LabelPass.setText("Password:");
        getContentPane().add(LabelPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, -1, -1));

        BtnAccesar.setBackground(new java.awt.Color(255, 255, 255));
        BtnAccesar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BtnAccesar.setText("Accesar");
        BtnAccesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAccesarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnAccesar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, 220, -1));

        TextUsuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TextUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(TextUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 220, -1));

        JSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/InicioSesion.png"))); // NOI18N
        getContentPane().add(JSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, -1));

        btnMin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Minimizar.png"))); // NOI18N
        btnMin.setAutoscrolls(true);
        btnMin.setBorder(null);
        btnMin.setBorderPainted(false);
        btnMin.setContentAreaFilled(false);
        btnMin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMin.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Minimizar3.png"))); // NOI18N
        btnMin.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Minimizar2.png"))); // NOI18N
        btnMin.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinActionPerformed(evt);
            }
        });
        getContentPane().add(btnMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, -1, -1));

        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Salir.png"))); // NOI18N
        btnCerrar.setAutoscrolls(true);
        btnCerrar.setBorder(null);
        btnCerrar.setBorderPainted(false);
        btnCerrar.setContentAreaFilled(false);
        btnCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCerrar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Salir3.png"))); // NOI18N
        btnCerrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Salir2.png"))); // NOI18N
        btnCerrar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, -1, -1));

        PasswordField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(PasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 220, -1));

        JFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo Negro.jpg"))); // NOI18N
        getContentPane().add(JFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextUsuarioActionPerformed

    private void BtnAccesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAccesarActionPerformed
        // TODO add your handling code here:
        String q = "from Usuario as u where u.idUsuario = " + TextUsuario.getText();
        Usuario u = executeHQLQuery(q);
        if(u != null){
            if (u.getPassword().equals(String.valueOf(PasswordField.getPassword()))) {
                if (u.getTipo().equals("1")) {
                    new Principal().setVisible(true);
                    this.setVisible(false);
                }
                else
                    JOptionPane.showMessageDialog(rootPane, "No puedes accesar ya que no eres Administrador");
            }
            else
                JOptionPane.showMessageDialog(rootPane, "Contraseña Incorrecta");
        }else
            JOptionPane.showMessageDialog(rootPane, "Usuario Inválido");
        
    }//GEN-LAST:event_BtnAccesarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinActionPerformed
        // TODO add your handling code here:
        this.setExtendedState(1);
    }//GEN-LAST:event_btnMinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioSesion().setVisible(true);
            }
        });
    }
    
    private Usuario executeHQLQuery(String hql) {
        List resultList = null;
        Usuario u = null;
        try {
            Session session = HibernateUtil.getSessionFactory().openSession();
            session.beginTransaction();
            Query q = session.createQuery(hql);
            resultList = q.list();
            
            for (Object o : resultList) {
                u = (Usuario)o;
            }
            session.getTransaction().commit();
            session.close();
        } catch (HibernateException he) {
            he.printStackTrace();
        }
        return u;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAccesar;
    private javax.swing.JLabel JFondo;
    private javax.swing.JLabel JSesion;
    private javax.swing.JLabel LabelPass;
    private javax.swing.JLabel LabelUsuario;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JTextField TextUsuario;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnMin;
    // End of variables declaration//GEN-END:variables
}
