<<<<<<< HEAD
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import bd.connection.Conexion;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.DefaultListModel;

/**
 *
 * @author luis_
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    Conexion conect = null;
    Connection con = null;
    DefaultListModel modeloLista = new DefaultListModel();


    public Principal() {
        initComponents();
         
        this.setLocationRelativeTo(null);
        conect = new Conexion("localhost", "3306", "mydb");
        con = conect.getConn();
        obtenerCatalogo_servicios();
        llenarLista_servicio();
        ListServicio.setModel(modeloLista);
        CmbCatalogo.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                llenarLista_servicio();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        btnCerrarSesion = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        btnMin = new javax.swing.JButton();
        CmbCatalogo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListServicio = new javax.swing.JList<>();
        BtnContrato = new javax.swing.JButton();
        JFondo = new javax.swing.JLabel();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CerrarSesion.png"))); // NOI18N
        btnCerrarSesion.setAutoscrolls(true);
        btnCerrarSesion.setBorder(null);
        btnCerrarSesion.setBorderPainted(false);
        btnCerrarSesion.setContentAreaFilled(false);
        btnCerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrarSesion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCerrarSesion.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CerrarSesion3.png"))); // NOI18N
        btnCerrarSesion.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CerrarSesion2.png"))); // NOI18N
        btnCerrarSesion.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        getContentPane().add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Salir.png"))); // NOI18N
        btnCerrar.setAutoscrolls(true);
        btnCerrar.setBorder(null);
        btnCerrar.setBorderPainted(false);
        btnCerrar.setContentAreaFilled(false);
        btnCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCerrar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Salir3.png"))); // NOI18N
        btnCerrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Salir2.png"))); // NOI18N
        btnCerrar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, -1, -1));

        btnMin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Minimizar.png"))); // NOI18N
        btnMin.setAutoscrolls(true);
        btnMin.setBorder(null);
        btnMin.setBorderPainted(false);
        btnMin.setContentAreaFilled(false);
        btnMin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMin.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Minimizar3.png"))); // NOI18N
        btnMin.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Minimizar2.png"))); // NOI18N
        btnMin.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinActionPerformed(evt);
            }
        });
        getContentPane().add(btnMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, -1, -1));

        CmbCatalogo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CmbCatalogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmbCatalogoActionPerformed(evt);
            }
        });
        getContentPane().add(CmbCatalogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 300, -1));

        jScrollPane1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        ListServicio.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(ListServicio);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 300, 80));

        BtnContrato.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BtnContrato.setText("Generar Contrato");
        getContentPane().add(BtnContrato, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 300, -1));
        

        JFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoNegro2.jpg"))); // NOI18N
        getContentPane().add(JFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 480));

        pack();
    }// </editor-fold>

    public void obtenerCatalogo_servicios() {
        String consulta_catalogo = "SELECT nombre FROM catalogo_servicios";
        try {
            PreparedStatement ps = con.prepareStatement(consulta_catalogo);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                CmbCatalogo.addItem(rs.getString(1));
            }

        } catch (SQLException ex) {
            System.out.println("Error en la consulta");
        }
    }

    public void llenarLista_servicio() {
        String consulta = "SELECT s.* from servicio s, catalogo_servicios c "
                + "where s.Catalogo_Servicios_idCS = c.idCS and c.Nombre like \"" + CmbCatalogo.getSelectedItem() + "\"";
        System.out.println(consulta);
        modeloLista.removeAllElements();
        try {
            String[] lista = new String[1];
            PreparedStatement ps = con.prepareStatement(consulta);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                lista[0] = rs.getString(2);
                modeloLista.addElement(lista[0]);
            }
        } catch (SQLException ex) {
            System.out.println("Error en la consulta");
        }
    }

    private void btnMinActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        this.setExtendedState(1);
    }

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        System.exit(0);
    }

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        new InicioSesion().setVisible(true);
        this.setVisible(false);
    }

    private void CmbCatalogoActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton BtnContrato;
    private javax.swing.JComboBox<String> CmbCatalogo;
    private javax.swing.JLabel JFondo;
    private javax.swing.JList<String> ListServicio;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnMin;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration
}
=======
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import bd.connection.Conexion;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.DefaultListModel;

/**
 *
 * @author luis_
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    Conexion conect = null;
    Connection con = null;
    DefaultListModel modeloLista = new DefaultListModel();
    String IDUsuario = null;

    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
        conect = new Conexion("localhost", "3306", "mydb");
        con = conect.getConn();
        obtenerCatalogo_servicios();
        llenarLista_servicio();
        ListServicio.setModel(modeloLista);
        CmbCatalogo.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                llenarLista_servicio();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        btnCerrarSesion = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        btnMin = new javax.swing.JButton();
        CmbCatalogo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListServicio = new javax.swing.JList<>();
        BtnContrato = new javax.swing.JButton();
        JFondo = new javax.swing.JLabel();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CerrarSesion.png"))); // NOI18N
        btnCerrarSesion.setAutoscrolls(true);
        btnCerrarSesion.setBorder(null);
        btnCerrarSesion.setBorderPainted(false);
        btnCerrarSesion.setContentAreaFilled(false);
        btnCerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrarSesion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCerrarSesion.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CerrarSesion3.png"))); // NOI18N
        btnCerrarSesion.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CerrarSesion2.png"))); // NOI18N
        btnCerrarSesion.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        getContentPane().add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Salir.png"))); // NOI18N
        btnCerrar.setAutoscrolls(true);
        btnCerrar.setBorder(null);
        btnCerrar.setBorderPainted(false);
        btnCerrar.setContentAreaFilled(false);
        btnCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCerrar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Salir3.png"))); // NOI18N
        btnCerrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Salir2.png"))); // NOI18N
        btnCerrar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, -1, -1));

        btnMin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Minimizar.png"))); // NOI18N
        btnMin.setAutoscrolls(true);
        btnMin.setBorder(null);
        btnMin.setBorderPainted(false);
        btnMin.setContentAreaFilled(false);
        btnMin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMin.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Minimizar3.png"))); // NOI18N
        btnMin.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Minimizar2.png"))); // NOI18N
        btnMin.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinActionPerformed(evt);
            }
        });
        getContentPane().add(btnMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, -1, -1));

        CmbCatalogo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CmbCatalogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmbCatalogoActionPerformed(evt);
            }
        });
        getContentPane().add(CmbCatalogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 300, -1));

        jScrollPane1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        ListServicio.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(ListServicio);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 300, 80));

        BtnContrato.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BtnContrato.setText("Generar Contrato");
        getContentPane().add(BtnContrato, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 300, -1));

        JFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoNegro2.jpg"))); // NOI18N
        getContentPane().add(JFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 480));

        pack();
    }// </editor-fold>

    public void obtenerCatalogo_servicios() {
        String consulta_catalogo = "SELECT nombre FROM catalogo_servicios";
        try {
            PreparedStatement ps = con.prepareStatement(consulta_catalogo);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                CmbCatalogo.addItem(rs.getString(1));
            }

        } catch (SQLException ex) {
            System.out.println("Error en la consulta");
        }
    }

    public void llenarLista_servicio() {
        String consulta = "SELECT s.* from servicio s, catalogo_servicios c "
                + "where s.Catalogo_Servicios_idCS = c.idCS and c.Nombre like \"" + CmbCatalogo.getSelectedItem() + "\"";
        System.out.println(consulta);
        modeloLista.removeAllElements();
        try {
            String[] lista = new String[1];
            PreparedStatement ps = con.prepareStatement(consulta);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                lista[0] = rs.getString(2);
                modeloLista.addElement(lista[0]);
            }
        } catch (SQLException ex) {
            System.out.println("Error en la consulta");
        }
    }

    private void btnMinActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        this.setExtendedState(1);
    }

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        System.exit(0);
    }

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        new InicioSesion().setVisible(true);
        this.setVisible(false);
    }

    private void CmbCatalogoActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton BtnContrato;
    private javax.swing.JComboBox<String> CmbCatalogo;
    private javax.swing.JLabel JFondo;
    private javax.swing.JList<String> ListServicio;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnMin;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration
}
>>>>>>> 9922223aaaa5350a68555cdb1e742d7113c16944
